### ISSUE TITLE
Links do not fit on a mobile

### ISSUE THREAD

**Issue by xparagon** [xparagon/hessdalen#5]
![Screenshot 2024-04-04 9 25 33 PM](https://github.com/xparagon/hessdalen/assets/35865041/aa054c38-9ed0-4a8c-a3c1-54741e56cfef)

On a narrow screen the links: web, blog and old - should be vertical not horizontal.

**Comment by mirsahib** [comment]
Hi @xparagon i would love to take a look at this

**Comment by xparagon** [comment]
Thanks @mirsahib - but no Pull request so I changed to this:
![on-mob](https://github.com/xparagon/hessdalen/assets/35865041/587ae583-e658-4f0c-9fb3-7f00dd4bea1e)
